export const CONTACT_PHONE_INTL = "919998986977";
export const CONTACT_PHONE_DISPLAY = "+91 99989-86977";
export const CONTACT_PHONE_TEL = `tel:+${CONTACT_PHONE_INTL}`;
export const CONTACT_WHATSAPP_URL = `https://wa.me/${CONTACT_PHONE_INTL}`;
